// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0LzEagnwXD2uR79KnRYycQVVc_5fSwY',
    appId: '1:154733788229:ios:e16d11057b08cfe344b72c',
    messagingSenderId: '154733788229',
    projectId: 'creati-calculator',
    storageBucket: 'creati-calculator.firebasestorage.app',
    iosBundleId: 'com.jhur.creaticalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0LzEagnwXD2uR79KnRYycQVVc_5fSwY',
    appId: '1:154733788229:ios:e16d11057b08cfe344b72c',
    messagingSenderId: '154733788229',
    projectId: 'creati-calculator',
    storageBucket: 'creati-calculator.firebasestorage.app',
    iosBundleId: 'com.jhur.creaticalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN40QaqZtz6FwM0SnUk9Iz_cgcYRGwmsw',
    appId: '1:154733788229:web:87b3cb89d5aa3def44b72c',
    messagingSenderId: '154733788229',
    projectId: 'creati-calculator',
    authDomain: 'creati-calculator.firebaseapp.com',
    storageBucket: 'creati-calculator.firebasestorage.app',
    measurementId: 'G-SFB89QJ77S',
  );
}
